# Generated by Django 3.2.3 on 2021-07-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('short_url', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('long_url', models.CharField(max_length=2048, unique=True)),
            ],
        ),
    ]
